In [5]:
import pandas as pd
data = [1,2,3,4]
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [16]:
data.index

<function list.index(value, start=0, stop=9223372036854775807, /)>

In [13]:
import pandas as pd
names=['hitesh','urvashi','shubham']
ages=[23,22,20]
data_frame =pd.DataFrame({'Names':names , 'Ages': ages})
print(data_frame)

     Names  Ages
0   hitesh    23
1  urvashi    22
2  shubham    20


In [15]:
import pandas as pd
_1 = pd.Series([1,2,3])
_2 = pd.Series([1,0,3])
_3 = pd.Series([0,2,3])
data_frame=pd.DataFrame({'A':_1,'B':_2,'C':_3})
print(data_frame)    


   A  B  C
0  1  1  0
1  2  0  2
2  3  3  3


In [1]:
import pandas as pd
data=pd.Series(5, index=[200,222,258])
print(data)

200    5
222    5
258    5
dtype: int64


In [39]:
import  pandas as pd
names=(['hitesh','shubham','urvashi','ketan'])
ages =[22,20,23,20]
address =['pune','vasai','bombay','guj']
phno=[999999999,5252525252,63632563,989899899]
data=pd.DataFrame({'Names':names,'Ages':ages,'Address':address,'Phone':phno }, index=['a','b','c','d'])

data

Names  Ages Address       Phone
a   hitesh    22    pune   999999999
b  shubham    20   vasai  5252525252
c  urvashi    23  bombay    63632563
d    ketan    20     guj   989899899

In [9]:
data.columns

Index(['Names', 'Ages', 'Address', 'Phone'], dtype='object')

In [10]:
data['Names']

0     hitesh
1    shubham
2    urvashi
3      ketan
Name: Names, dtype: object

In [15]:
import pandas as pd
data=pd.DataFrame({'A':i,'B':2*i}
for i in range(5))
print (data)

   1  2
0  0  0
1  1  2
2  2  4
3  3  6
4  4  8


In [16]:
indA=pd.Index([1,2,3,4,5,6,8])
indB=pd.Index([0,2,3,9,5,6,11])
indA & indB

Int64Index([2, 3, 5, 6], dtype='int64')

In [17]:
indA|indB

Int64Index([0, 1, 2, 3, 4, 5, 6, 8, 9, 11], dtype='int64')

In [18]:
indA^indB

Int64Index([0, 1, 4, 8, 9, 11], dtype='int64')

In [47]:
#Advance in DataFrame usning Pandas

import pandas as pd
city=['adalaj','vasai','surat','narasopara','akurdi','talegaon']
pop=[96964496,12142121,30242215,45445525,45454534,52532521]
area=[36000,51232,56565,200007,789652,656565]
data=pd.DataFrame({'Population':pop ,'Area':area,'City':city})
print(data)

   Population    Area        City
0    96964496   36000      adalaj
1    12142121   51232       vasai
2    30242215   56565       surat
3    45445525  200007  narasopara
4    45454534  789652      akurdi
5    52532521  656565    talegaon


In [60]:
data['density']= data['Population']/data['Area']

In [59]:
data['density']

0    2693.458222
1     237.002674
2     534.645364
3     227.219672
4      57.562742
5      80.011150
Name: density, dtype: float64

In [61]:
data

Population    Area        City      density
0    96964496   36000      adalaj  2693.458222
1    12142121   51232       vasai   237.002674
2    30242215   56565       surat   534.645364
3    45445525  200007  narasopara   227.219672
4    45454534  789652      akurdi    57.562742
5    52532521  656565    talegaon    80.011150

In [62]:
data.values

array([[96964496, 36000, 'adalaj', 2693.458222222222],
       [12142121, 51232, 'vasai', 237.0026741099313],
       [30242215, 56565, 'surat', 534.6453637408291],
       [45445525, 200007, 'narasopara', 227.2196723114691],
       [45454534, 789652, 'akurdi', 57.56274156210584],
       [52532521, 656565, 'talegaon', 80.0111504573043]], dtype=object)

In [63]:
data.T

0         1         2           3         4         5
Population  96964496  12142121  30242215    45445525  45454534  52532521
Area           36000     51232     56565      200007    789652    656565
City          adalaj     vasai     surat  narasopara    akurdi  talegaon
density      2693.46   237.003   534.645      227.22   57.5627   80.0112

In [64]:
data.iloc[:3,:2]

Population   Area
0    96964496  36000
1    12142121  51232
2    30242215  56565

In [68]:
data.loc[:3,:'Area']

Population    Area
0    96964496   36000
1    12142121   51232
2    30242215   56565
3    45445525  200007

In [69]:
data[data.density>200]

Population    Area        City      density
0    96964496   36000      adalaj  2693.458222
1    12142121   51232       vasai   237.002674
2    30242215   56565       surat   534.645364
3    45445525  200007  narasopara   227.219672

In [71]:
data.iloc[0,3]=200

Population    Area        City     density
0    96964496   36000      adalaj  200.000000
1    12142121   51232       vasai  237.002674
2    30242215   56565       surat  534.645364
3    45445525  200007  narasopara  227.219672
4    45454534  789652      akurdi   57.562742
5    52532521  656565    talegaon   80.011150

In [15]:
#random pandas and numpy
import pandas as pd
import numpy as np
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,5))
ser


0    6
1    3
2    7
3    4
4    6
dtype: int64

In [29]:
#random




import numpy as np
import pandas as pd
import random


data = np.random.random((3,2,3)) # (3,2,3) this will print 3 times between 2 and 3

data




array([[[0.51222435, 0.11170388, 0.73436563],
        [0.73068626, 0.68597865, 0.57471473]],

       [[0.62024838, 0.76844659, 0.31298635],
        [0.37415946, 0.8592821 , 0.97606355]],

       [[0.3972543 , 0.65202449, 0.44725098],
        [0.63854936, 0.38910129, 0.74289649]]])

In [31]:
#Random



import numpy as np
import pandas as pd
import random

data = np.random.randn(2,3) #this randn will give us negative matrix
data


array([[-1.35482091,  1.12156913, -0.93447189],
       [ 1.35957701, -1.24757867, -0.83086747]])

In [1]:

import numpy as np
import pandas as pd
import random

name = ['hitesh','shubhsm','ketan','urvashi']
data=np.random.choice(name,size=(3,3),p=[0,1,0,0])
data


array([['shubhsm', 'shubhsm', 'shubhsm'],
       ['shubhsm', 'shubhsm', 'shubhsm'],
       ['shubhsm', 'shubhsm', 'shubhsm']], dtype='<U7')

In [52]:
#Random



import numpy as np
import pandas as pd
import random

name = ['hitesh','shubhsm','ketan','urvashi']
data=np.random.choice(name,size=(3,3),p=[0,1,0,0])
data


array([['shubhsm', 'shubhsm', 'shubhsm'],
       ['shubhsm', 'shubhsm', 'shubhsm'],
       ['shubhsm', 'shubhsm', 'shubhsm']], dtype='<U7')

In [54]:

import numpy as np
import pandas as pd
import random

name = ['hitesh','shubhsm','ketan','urvashi']
data=np.random.choice(name,size=(3,3),p=[0.2,0.5,0,0.3])  #occuring of the elements as per the given percentage
data


array([['shubhsm', 'hitesh', 'shubhsm'],
       ['hitesh', 'shubhsm', 'hitesh'],
       ['urvashi', 'shubhsm', 'shubhsm']], dtype='<U7')

In [17]:
import pandas as pd
import numpy as np
#rng =np.random.RandomState(42)
data = pd.DataFrame(np.random.randint(1,10,size=(3,3)), columns =['A','B','C']) 
'''' this can work both the way. If we remove # from third line the code will run. 
but on third line we have to put'rng.randint()' instead of'np.random.randint()'. '''                                                                          
data

A  B  C
0  2  7  2
1  2  8  9
2  2  1  6

In [18]:
import pandas as pd
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [20]:
#multiIndex Creations



import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.806183  0.167066
  2  0.440716  0.910857
b 1  0.667650  0.544792
  2  0.067729  0.158915

In [7]:
#MultiIndexing

import numpy as np
import pandas as pd

'''
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data
'''

index = pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])
columns = pd.MultiIndex.from_product([['bob','huh','iji'],['Hr','Temp']], names=['subject','type'])
data =np.round(np.random.rand(4,6),1)   # the 1 in the end will take only one value after decomal point
data[:, ::2]*=10
data+=37

health=pd.DataFrame(data,index=index,columns=columns)
health


subject      bob         huh         iji      
type          Hr  Temp    Hr  Temp    Hr  Temp
year visit                                    
2013 1      45.0  37.1  38.0  37.7  45.0  37.2
     2      45.0  37.5  39.0  37.0  44.0  37.5
2014 1      43.0  37.0  45.0  37.8  38.0  37.5
     2      43.0  38.0  44.0  37.5  38.0  37.5

In [9]:
idx = pd.IndexSlice
health_data.loc[idx[:, 2], idx[:, 'HR']]

NameError: name 'health_data' is not defined